-- Copyright (C) 2022  Frédéric France     <frederic.france@netlogic.fr>
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see http://www.gnu.org/licenses/.


-- ALTER TABLE llx_dolitrashcan ADD INDEX idx_dolitrashcan_ref (ref);
-- ALTER TABLE llx_dolitrashcan ADD INDEX idx_dolitrashcan_entity (entity);
-- ALTER TABLE llx_dolitrashcan ADD INDEX idx_dolitrashcan_fk_soc (fk_soc);
-- ALTER TABLE llx_dolitrashcan ADD INDEX idx_dolitrashcan_status (status);
-- ALTER TABLE llx_dolitrashcan ADD INDEX idx_dolitrashcan_fk_object (fk_object);
